In [3]:
# Install visualization libraries

%pip install plotly matplotlib seaborn ipython nbformat

print("Visualization libraries installed.")

Requirement already satisfied: plotly in c:\python312\lib\site-packages (6.6.0)
Requirement already satisfied: matplotlib in c:\python312\lib\site-packages (3.10.7)
Requirement already satisfied: seaborn in c:\python312\lib\site-packages (0.13.2)
Requirement already satisfied: ipython in c:\users\user\appdata\roaming\python\python312\site-packages (9.7.0)
Requirement already satisfied: nbformat in c:\python312\lib\site-packages (5.10.4)
Requirement already satisfied: narwhals>=1.15.1 in c:\python312\lib\site-packages (from plotly) (2.17.0)
Requirement already satisfied: packaging in c:\python312\lib\site-packages (from plotly) (24.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\python312\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\python312\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python312\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\python312\lib\site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: pillow>=8 in c:\python312\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\python312\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\python312\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython) (5.14.3)
Requirement already satisfied: wcwidth in c:\python312\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.2.13)
Requirement already satisfied: fastjsonschema>=2.15 in c:\python312\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\python312\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\user\appdata\roaming\python\python312\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\user\appdata\roaming\python\python312\site-packages (from jedi>=0.18.1->ipython) (0.8.5)
Requirement already satisfied: attrs>=22.2.0 in c:\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\python312\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\user\appdata\roaming\python\python312\site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Note: you may need to restart the kernel to use updated packages.
Visualization libraries installed.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# import pandas for data manipulation
import pandas as pd

# import plotly express for interactive visualizations
import plotly.express as px

print("Libraries loaded")

Libraries loaded

In [5]:
# load dengue dataset
data = pd.read_csv("../data/raw/dengue_dataset_original.csv")

# display first 5 rows
data.head()

,moh_area,week,cases,avg_temperature_mean,avg_temperature_max,avg_temperature_min,avg_precipitation_sum,avg_relative_humidity_mean
0,MOH-Addalachchenai,1,5.0,25.886309,28.278570,23.964285,7.628572,87.357422
1,MOH-Addalachchenai,2,3.0,25.955952,28.042858,24.285715,16.328571,82.071373
2,MOH-Addalachchenai,3,8.0,25.662798,28.635714,22.821428,2.471429,83.079887
3,MOH-Addalachchenai,4,11.0,26.674702,29.464285,23.378571,0.742857,72.721458
4,MOH-Addalachchenai,5,4.0,26.046429,29.228573,23.542858,6.642857,86.899406

In [6]:
# summary statistics - to find abnormilities
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
week,38691.0,53.501383,30.599411,1.00000,27.000000,54.000000,80.000000,107.00000
cases,38690.0,2.611889,5.080387,0.00000,0.000000,1.000000,3.000000,196.00000
avg_temperature_mean,38689.0,26.157421,2.317103,14.13344,25.154170,26.275890,27.600595,36.87143
avg_temperature_max,38689.0,30.180132,2.805926,15.82600,28.707140,29.935710,31.935710,39.00714
avg_temperature_min,38689.0,23.169247,2.568002,0.00000,22.335710,23.514290,24.692858,79.72857
avg_precipitation_sum,38689.0,7.245722,8.957673,0.00000,1.742857,4.728571,9.371428,92.48659
avg_relative_humidity_mean,38583.0,81.882345,7.421703,21.83602,77.555920,83.499200,87.190180,98.73265

In [7]:
# print the number of rows and cols
data.shape

(38691, 8)

In [8]:
# check missing values of each column
data.isnull().sum()

moh_area                        0
week                            0
cases                           1
avg_temperature_mean            2
avg_temperature_max             2
avg_temperature_min             2
avg_precipitation_sum           2
avg_relative_humidity_mean    108
dtype: int64

In [ ]:
import plotly.express as px

#histogram - helps identify extreme case counts
cases_hist = px.histogram(
    data,
    x="cases",
    title="Distribution of Dengue Cases"
)

cases_hist.show()

In [ ]:
#detect extreme case spikes
cases_box = px.box(
    data,
    x="cases",
    title="Box Plot of Dengue Cases"
)

cases_box.show()

In [ ]:
#detect extreme rain spikes 
rain_box = px.box(
    data,
    x="avg_precipitation_sum",
    title="Box Plot of Rainfall"
)

rain_box.show()

In [12]:
#shows the relationship between rainfall and dengue cases
rain_cases = px.scatter(
    data,
    x="avg_precipitation_sum",
    y="cases",
    title="Rainfall vs Dengue Cases"
)

rain_cases.show()

In [13]:
#shows relationship between temperature and dengue cases
temp_cases = px.scatter(
    data,
    x="avg_temperature_mean",
    y="cases",
    title="Temperature vs Dengue Cases"
)

temp_cases.show()

In [ ]:
#shows how dengue evolved over time
area_data = data[data["moh_area"] == data["moh_area"].unique()[0]]

trend_plot = px.line(
    area_data,
    x="week",
    y="cases",
    title="Weekly Dengue Cases Trend"
)

trend_plot.show()

In [ ]:
#shows how temperature affected the dengue case counts over time
temp_hist = px.histogram(
    data,
    x="avg_temperature_mean",
    color="moh_area",
    title="Temperature Distribution by MOH Area",
    barmode="overlay"
)

temp_hist.show()